ATTPC/ATTPCROOTv2

- macro/examples/run_hierarchical_clustering.C
- reco/ATDecoder/ATHit.cc
- reco/ATDecoder/ATHit.hh
- reco/ATHierarchicalClusteringTask.cc
- reco/ATHierarchicalClusteringTask.hh
- reco/HierarchicalClustering/ATHierarchicalClusteringCluster.cc
- reco/HierarchicalClustering/ATHierarchicalClusteringCluster.hh
- reco/HierarchicalClustering/ATHierarchicalClusteringHc.cc
also added `const` to `ATHit` getters and fixed a typo in a filename
still needs to be tested (*.root file needed)
> WIP: hierarchical clustering integrated with new types

- .gitignore
- macro/examples/run_hierarchical_clustering.C
- reco/ATHierarchicalClusteringTask.cc
- reco/HierarchicalClustering/ATHierarchicalClusteringCluster.cc
- reco/HierarchicalClustering/ATHierarchicalClusteringCluster.hh
- reco/HierarchicalClustering/ATHierarchicalClusteringHc.cc
- reco/HierarchicalClustering/ATHierarchicalClusteringHc.hh
- reco/HierarchicalClustering/ATHierarchicalClusteringSmoothenCloud.cc
- reco/HierarchicalClustering/ATHierarchicalClusteringSmoothenCloud.hh
fixed https://github.com/ATTPC/ATTPCROOTv2/issues/10
> Done: fixed Issue #10

- macro/export/root_to_json.C
- macro/export/root_to_pcl.C
fixed pcl exporter
added json exporter
I was told an exporter with fileFormats readable by python could be useful. So I started one.
> Done: exporters

- AtGenerators/ATTPCFissionGeneratorV2.cxx
- AtGenerators/ATTPCFissionGeneratorV2.h
- digi/ATClusterizeTask.cc
- digi/ATPulseTask.cc
- digi/ATPulseTask.hh
Modified simulation setup for a working fission fragment simulation
> Modified simulation to work

- macro/examples/run_hierarchical_clustering.C
- reco/ATHierarchicalClusteringTask.cc
- reco/ATHierarchicalClusteringTask.hh
removed cloudScale calculation to have codebase in sync with dalitz' version
> removed cloudScale calculation

- digi/ATClusterizeTask.cc
- digi/ATClusterizeTask.hh
- digi/ATPulseTask.cc
- digi/ATPulseTask.hh
- digi/ATSimulatedPoint.cc
- macro/e15250/digi/AT.C
- macro/e15250/digi/rundigi_sim.C
- parameters/AT.digi.par
The commit includes a macro for the fast analysis (macro/e15250/digi/AT.C) and many
corrections. GET gain is hardcoded, should be added to the digi parameter list.
> Correct cluster and pulse formation with proper GET gain

- eventdisplayAT/ATEventDrawTask.cc
- eventdisplayAT/ATEventDrawTask.hh
- macro/Simulation/d2He/compilar.sh
- reco/ATRansac/ATRansac.cc
- reco/ATRansac/ATRansac.hh
- reco/ATRansacTask.cc
Created a new branch "single_commit" based on  origin ATTPCROOTv2/develop for creating pull requests
> Single commit

- eventdisplayAT/ATEventDrawTask.cc
- eventdisplayAT/ATEventDrawTask.hh
- eventdisplayAT/ATEventManager.cc
- eventdisplayAT/ATEventManager.hh
Right now supports up to 9 aux channels
> Add aux channels to the event visualized for attpc

- macro/Unpack_HDF5/e18008_S800/compilar.sh
- macro/Unpack_HDF5/e18008_S800/load_env.sh
- macro/Unpack_HDF5/e18008_S800/unpack_new.C
- reco/ATPSATask.cc
- reco/ATPSATask.hh
- reco/ATPulseAnalyzer/ATPSA.cc
- reco/ATPulseAnalyzer/ATPSA.hh
- reco/ATPulseAnalyzer/ATPSAFilter.cc
- reco/ATPulseAnalyzer/ATPSASimple2.cc
Simple BG interpolation using TSpectrum
> Background interpolation

- digi/ATPulseTask.cc
- parameters/ATTPC.d2HeSim.par
in ATPulseTask, polya gain factor averaged on pad electrons.
> average pad gain fluctuation

- geometry/GADGET_II.C
Added more components to detector geometry (end caps, cathode, micromegas, etc.). Ran git clang-format command on staged file.
> Tyler fork

- AtReconstruction/AtSpaceChargeCorrectionTask.cxx
- AtTools/AtLineChargeModel.cxx
- AtTools/AtLineChargeModel.h
- AtTools/AtRadialChargeModel.cxx
- AtTools/AtRadialChargeModel.h
- AtTools/AtSpaceChargeModel.cxx
- AtTools/AtSpaceChargeModel.h
- AtTools/AtToolsLinkDef.h
- AtTools/CMakeLists.txt
- macro/e12014/adam/spaceCharge/run_eve.C
- macro/e12014/adam/spaceCharge/test.C
- macro/e12014/adam/spaceCharge/unpack.C
AtSpaceChargeModels, when used in a task, will also pull the values
they need from AtDigiPar.
Fix bug in AtLineChargeModel, there was a missing factor of 2.
> Add space charge model for arbitrary radial field.

- AtReconstruction/AtFitter/AtFitter.cxx
- AtReconstruction/AtFitter/AtFitter.h
- AtReconstruction/AtPRAtask.cxx
- AtReconstruction/AtPRAtask.h
- AtReconstruction/AtPatternRecognition/AtPRA.cxx
- AtReconstruction/AtPatternRecognition/AtPRA.h
- AtReconstruction/AtPatternRecognition/AtTrackFinderTC.cxx
- AtReconstruction/AtPulseAnalyzer/AtPSASimple2.cxx
- AtSiArray/AtSiPoint.cxx
- AtSiArray/AtSiPoint.h
- AtTools/AtToolsLinkDef.h
- AtTools/AtTrackTransformer.cxx
- AtTools/AtTrackTransformer.h
- compiled/EFitterAnalysis/eFitterAnalysis.h
> Add missing function implementations.

- AtEventDisplay/AtEventDrawTask.cxx
> Fix nullptr exception when map is not set in viewer

- AtGenerators/AtTPCIonGenerator.cxx
- AtGenerators/AtTPCIonGenerator.h
Add option to disable reaction in simulation. Add method to set beam
emittance in simulation.
> Add additional options for beam simulation

- AtGenerators/AtTPC20MgDecay.cxx
- AtGenerators/AtTPC20MgDecay.h
- AtTools/AtKinematics.cxx
- AtTools/AtVirtualTerminal.cxx
- scripts/updateIfs.sh
@Yassid Don't worry about this PR, I'm working with Ruchi to cleanup the generator.
> Cleanup AtTPC20MgDecay so it passes code linters

- AtMap/AtSpecMATMap.h
- geometry/SpecMAT_He1Bar_v2.C
- macro/Simulation/SpecMAT/86Kr_He4He3/Kr86_He4He3_sim.C
- macro/Simulation/SpecMAT/86Kr_He4He3/eventDisplay.C
- macro/Simulation/SpecMAT/86Kr_He4He3/run_eve.C
- macro/Simulation/SpecMAT/86Kr_He4He3/rundigi_sim.C
- parameters/SpecMAT.run_9901.par
Added a new simulation for the specmat detector for the Kr86(He4,He3)Kr87 reaction.
> Specmat simulations

- AtEventDisplay/AtSidebar/AtSidebarAddon.cxx
- AtEventDisplay/AtSidebar/AtSidebarAddon.h
- AtEventDisplay/AtSidebar/PSA/AtSidebarPSA.cxx
- AtEventDisplay/AtSidebar/PSA/AtSidebarPSADeconv.cxx
- AtEventDisplay/AtSidebar/PSA/AtSidebarPSAIterDeconv.cxx
Adding a commit from Curtis branch that I missed when putting the full viewer PR together.
> Added documentation to AtSidebarAddon

- AtEventDisplay/AtEventDisplayLinkDef.h
- AtEventDisplay/AtSidebar/AtSidebarAddon.cxx
- AtEventDisplay/AtSidebar/AtSidebarAddon.h
- AtEventDisplay/AtSidebar/AtSidebarInfoMacro.cxx
- AtEventDisplay/AtSidebar/AtSidebarInfoMacro.h
- AtEventDisplay/AtTabs/AtTabMacro.cxx
- AtEventDisplay/AtTabs/AtTabMacro.h
- AtEventDisplay/CMakeLists.txt
Added ability to put an info box in AtSidebarAddons. Implemented in AtSidebarInfoMacro to output string from function.
Updated AtTabMacro constructor to match AtTabPad and fixed a few errors in the canvas.
> AtSidebarAddons additions and minor AtTabMacro mods and fixes

- AtEventDisplay/AtSidebar/AtSidebarFrames.cxx
After last commit, the subject will rerun the event on call to Set(). Notify just lets people know the event may have changed.
> Rerun Event button reruns instead of redraws the event.

- AtTools/AtKinematics.cxx
> Fixed error that prevents compilation

- AtReconstruction/AtFitter/AtOpenKFTest.cxx
- AtReconstruction/AtFitter/AtOpenKFTest.h
See AtReconstruction/CMakeLists.txt and AtReconstruction/AtFitter/AtOpenKFTest.h for how to link against the OpenKF headers
> Add OpenKF as an optional dependecy
